name: Label Pull Request

description: 'Labels a pull request based on review status'

author: 'Leonardo Natera'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
    default: '${{ secrets.GITHUB_TOKEN }}'
  pull-request-number:
    description: 'Number of the pull request'
    required: true

branding:
    icon: 'check-square'
    color: 'blue'

runs:
  using: 'docker'
  image: 'leonerrr/pull-request-labeler:latest'
  entrypoint: '/scripts/label-pull-request.sh'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
