name: publish

on:
  push:
    branches: [ 'main' ]

jobs:
  publish-action-docker-image:
    runs-on: ubuntu-latest
    environment: docker-image-builder

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building pull-request-labeler docker image
        run: |
          docker build .  --tag ghcr.io/mr-leonerrr/labeler-actions:1.0.1 --tag ghcr.io/mr-leonerrr/labeler-actions:latest
          docker push ghcr.io/mr-leonerrr/labeler-actions:1.0.1
          docker push ghcr.io/mr-leonerrr/labeler-actions:latest
